// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB4Br4Z9D_nRV45tFiyW0wniWVxL5z91E',
    appId: '1:930596237188:web:489f53573000dd223df7d1',
    messagingSenderId: '930596237188',
    projectId: 'shop-app-37fc8',
    authDomain: 'shop-app-37fc8.firebaseapp.com',
    storageBucket: 'shop-app-37fc8.firebasestorage.app',
    measurementId: 'G-LFRPPB5TER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjakwycSiRcPBvFsQ96WvicE4K2aODVAU',
    appId: '1:930596237188:android:3d1f4a8e92b82a823df7d1',
    messagingSenderId: '930596237188',
    projectId: 'shop-app-37fc8',
    storageBucket: 'shop-app-37fc8.firebasestorage.app',
  );
}
