// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxf1YHasO6map_2_ZA6cB3pnMcNE8I10w',
    appId: '1:103802962873:web:5ba441dc5c6c1a9acbec68',
    messagingSenderId: '103802962873',
    projectId: 'uas-sp-mobile',
    authDomain: 'uas-sp-mobile.firebaseapp.com',
    storageBucket: 'uas-sp-mobile.firebasestorage.app',
    measurementId: 'G-CT5TTVP11F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5XVIQsoNelsdOuWZfN-NCRCue1AD5h-Q',
    appId: '1:103802962873:android:054a389ed4d3ae6ccbec68',
    messagingSenderId: '103802962873',
    projectId: 'uas-sp-mobile',
    storageBucket: 'uas-sp-mobile.firebasestorage.app',
  );

}